/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Service.DiemService;
import entity.Diem;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tt
 */
public class QLDFrame extends javax.swing.JFrame {

    /**
     * Creates new form QLDFrame
     */
    private int index = -1;
    private DiemService diemSV;
    public QLDFrame() {
        initComponents();
        icon();
        txt_HoTensvvv.setEnabled(false);
        diemSV = new DiemService();
        diemSV.save(new Diem(1, "Hoàng Vĩnh Giang", 9, 9, 9, 9));
        diemSV.save(new Diem(2, "Đặng Thanh Phương", 10, 10, 10, 10));
        diemSV.save(new Diem(3, "Dương Văn Cảnh", 10, 10, 10, 10));
        loadTable(diemSV.getListD());
    }
    public void loadTable(ArrayList<Diem> arD){
        DefaultTableModel defaultTableModel = (DefaultTableModel) tb_QLDSV.getModel();
        defaultTableModel.setRowCount(0);
        for (Diem d :arD) {
            Object[] rowData = {
                d.getMaSV(),
                d.getHoTen(),
                d.getTiengAnh(),
                d.getTinHoc(),
                d.getGDTC(),
                d.getDiemTB()
            };
            defaultTableModel.addRow(rowData);
        }
    }
    public void icon() {
        Icon icon = new ImageIcon("search.png");
        Icon icon1 = new ImageIcon("plus.png");
        Icon icon2 = new ImageIcon("save.png");
        Icon icon3 = new ImageIcon("cancel.png");
        Icon icon4 = new ImageIcon("pencil.png");
        Icon icon5 = new ImageIcon("1.png");
        Icon icon6 = new ImageIcon("2.png");
        Icon icon7 = new ImageIcon("3.png");
        Icon icon8 = new ImageIcon("4.png");
        this.btn_new.setIcon(icon1);
        this.btn_delete.setIcon(icon3);
        this.btn_save.setIcon(icon2);
        this.btn_update.setIcon(icon4);
        this.btn_search.setIcon(icon);

        this.btn1.setIcon(icon5);
        this.btn1.setText("");
        this.btn2.setIcon(icon6);
        this.btn2.setText("");
        this.btn3.setIcon(icon7);
        this.btn3.setText("");
        this.btn4.setIcon(icon8);
        this.btn4.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_masVV = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_HoTensvvv = new javax.swing.JTextField();
        txt_Masvvv = new javax.swing.JTextField();
        txt_TiengAnh = new javax.swing.JTextField();
        txt_TinHoc = new javax.swing.JTextField();
        txt_GDTC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_DiemTB = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_QLDSV = new javax.swing.JTable();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Quản Lý Điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel1.setText("Mã SV:");

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_masVV, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_masVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Họ và tên SV:");

        jLabel4.setText("Mã SV:");

        jLabel5.setText("Tiếng anh:");

        jLabel6.setText("Tin học:");

        jLabel7.setText("Giáo dục TC:");

        txt_HoTensvvv.setForeground(new java.awt.Color(0, 0, 255));
        txt_HoTensvvv.setText("-");

        txt_TinHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TinHocActionPerformed(evt);
            }
        });

        jLabel8.setText("Điểm TB");

        txt_DiemTB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_DiemTB.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_HoTensvvv, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_GDTC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_TiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(txt_DiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_TinHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Masvvv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_HoTensvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Masvvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_TiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_DiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_GDTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn2.setText("jButton6");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("jButton7");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("jButton8");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("3 sinh viên có điểm cao nhất");

        tb_QLDSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "Tiếng anh", "Tin học", "GDTC", "Điểm TB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tb_QLDSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_QLDSVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_QLDSV);

        btn1.setText("jButton1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_save)
                                            .addComponent(btn_new)
                                            .addComponent(btn_delete)
                                            .addComponent(btn_update)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btn1)
                                .addGap(18, 18, 18)
                                .addComponent(btn2)
                                .addGap(18, 18, 18)
                                .addComponent(btn3)
                                .addGap(18, 18, 18)
                                .addComponent(btn4)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_save)
                        .addGap(26, 26, 26)
                        .addComponent(btn_new)
                        .addGap(30, 30, 30)
                        .addComponent(btn_delete)
                        .addGap(33, 33, 33)
                        .addComponent(btn_update)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(btn1))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TinHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TinHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TinHocActionPerformed
    public void truoc() {
        if (index >= diemSV.getListD().size() - 1) {
            Frist();
        } else {
            index++;
            tb_QLDSV.setRowSelectionInterval(index, index);
        txt_Masvvv.setText(tb_QLDSV.getValueAt(index, 0).toString());
        txt_HoTensvvv.setText(tb_QLDSV.getValueAt(index, 1).toString());
        txt_TiengAnh.setText(tb_QLDSV.getValueAt(index, 2).toString());
        txt_TinHoc.setText(tb_QLDSV.getValueAt(index, 3).toString());
        txt_GDTC.setText(tb_QLDSV.getValueAt(index, 4).toString());
        txt_DiemTB.setText(tb_QLDSV.getValueAt(index, 5).toString());
        }
        
    }
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        truoc();
    }//GEN-LAST:event_btn2ActionPerformed
    private void clearForm(){
        txt_HoTensvvv.setText("");
        txt_DiemTB.setText("");
        txt_GDTC.setText("");
        txt_Masvvv.setText("");
        txt_TiengAnh.setText("");
        txt_TinHoc.setText("");
    }
    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        clearForm();
    }//GEN-LAST:event_btn_newActionPerformed

    private void tb_QLDSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_QLDSVMouseClicked
        int row = tb_QLDSV.getSelectedRow();
        if(row==-1){
            return;
        }
        String MaSV = tb_QLDSV.getValueAt(row, 0).toString();
        String hoten = tb_QLDSV.getValueAt(row, 1).toString();
        String TA = tb_QLDSV.getValueAt(row, 2).toString();
        String Tin = tb_QLDSV.getValueAt(row, 3).toString();
        String GDTC = tb_QLDSV.getValueAt(row, 4).toString();
        String DiemTB = tb_QLDSV.getValueAt(row, 5).toString();
        
        txt_Masvvv.setText(MaSV);
        txt_HoTensvvv.setText(hoten);
        txt_TiengAnh.setText(TA);
        txt_TinHoc.setText(Tin);
        txt_GDTC.setText(GDTC);
        txt_DiemTB.setText(DiemTB);
    }//GEN-LAST:event_tb_QLDSVMouseClicked
    private Diem getFormData(){
        String MaSV = txt_Masvvv.getText().trim();
        String hoten = txt_HoTensvvv.getText().trim();
        String TA = txt_TiengAnh.getText().trim();
        String Tin = txt_TinHoc.getText().trim();
        String GDTC = txt_GDTC.getText().trim();
        if(
                MaSV.length()==0||
                hoten.length()==0||
                TA.length()==0||
                Tin.length()==0||
                GDTC.length()==0
                ){
            JOptionPane.showMessageDialog(this, "Thông tin không được để trống");
            return null;
        }
        int diemTA=-1;
        int diemTin=-1;
        int diemGDTC=-1;
        
            
            
        try {
            diemTA=Integer.parseInt(TA);
            
            if(diemTA<0){
                JOptionPane.showMessageDialog(this, "Điểm phải là số dương");
                return null;
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Điểm phải là số nguyên");
            return null;
        }
        try {
            diemTin=Integer.parseInt(Tin);
            
            if(diemTin<0){
                JOptionPane.showMessageDialog(this, "Điểm phải là số dương");
                return null;
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Điểm phải là số nguyên");
            return null;
        }
        try {
            diemGDTC=Integer.parseInt(GDTC);
            
            if(diemGDTC<0){
                JOptionPane.showMessageDialog(this, "Điểm phải là số dương");
                return null;
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Điểm phải là số nguyên");
            return null;
        }
        int diemTB = (diemTA+diemTin+diemGDTC)/3;
        Diem d = new Diem(Integer.parseInt(MaSV), hoten, diemTA, diemTin, diemGDTC, diemTB);
        return d;
    }
    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        Diem d = this.getFormData();
        if(d==null){
            return;
        }
        this.diemSV.save(d);
        this.loadTable(diemSV.getListD());
        this.clearForm();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int row = tb_QLDSV.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng để cập nhập");
            return;
        }
        
        Diem d =this.getFormData();
        if(d==null){
            return;
            }

        this.diemSV.update(d.getMaSV(), d);
        this.loadTable(diemSV.getListD());
        this.clearForm();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int row = tb_QLDSV.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng rồi xóa");
            return;
        }
        int xacnhan = JOptionPane.showConfirmDialog(this, "Xác nhận xóa?");
        if(xacnhan!=JOptionPane.YES_OPTION){
            return;
        }
        
        String maSv = this.tb_QLDSV.getValueAt(row, 0).toString();
        this.diemSV.delete(Integer.parseInt(maSv));
        this.loadTable(diemSV.getListD());
        this.clearForm();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String maNv = txt_masVV.getText();
        int manv = Integer.parseInt(maNv);
        ArrayList<Diem> listD = diemSV.search(diemSV.getListD(),manv);
        loadTable(listD);
        txt_masVV.setText("");
    }//GEN-LAST:event_btn_searchActionPerformed
public void Frist() {
        index = 0;
        tb_QLDSV.setRowSelectionInterval(index, index);
        txt_Masvvv.setText(tb_QLDSV.getValueAt(index, 0).toString());
        txt_HoTensvvv.setText(tb_QLDSV.getValueAt(index, 1).toString());
        txt_TiengAnh.setText(tb_QLDSV.getValueAt(index, 2).toString());
        txt_TinHoc.setText(tb_QLDSV.getValueAt(index, 3).toString());
        txt_GDTC.setText(tb_QLDSV.getValueAt(index, 4).toString());
        txt_DiemTB.setText(tb_QLDSV.getValueAt(index, 5).toString());
    }
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Frist();
    }//GEN-LAST:event_btn1ActionPerformed
    public void Last() {
        index = diemSV.getListD().size() - 1;
        tb_QLDSV.setRowSelectionInterval(index, index);
        txt_Masvvv.setText(tb_QLDSV.getValueAt(index, 0).toString());
        txt_HoTensvvv.setText(tb_QLDSV.getValueAt(index, 1).toString());
        txt_TiengAnh.setText(tb_QLDSV.getValueAt(index, 2).toString());
        txt_TinHoc.setText(tb_QLDSV.getValueAt(index, 3).toString());
        txt_GDTC.setText(tb_QLDSV.getValueAt(index, 4).toString());
        txt_DiemTB.setText(tb_QLDSV.getValueAt(index, 5).toString());
    }
    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        Last();
    }//GEN-LAST:event_btn4ActionPerformed
    public void truoc1() {
        if (index <= 0) {
            Last();
        } else {
            index--;
            tb_QLDSV.setRowSelectionInterval(index, index);
        txt_Masvvv.setText(tb_QLDSV.getValueAt(index, 0).toString());
        txt_HoTensvvv.setText(tb_QLDSV.getValueAt(index, 1).toString());
        txt_TiengAnh.setText(tb_QLDSV.getValueAt(index, 2).toString());
        txt_TinHoc.setText(tb_QLDSV.getValueAt(index, 3).toString());
        txt_GDTC.setText(tb_QLDSV.getValueAt(index, 4).toString());
        txt_DiemTB.setText(tb_QLDSV.getValueAt(index, 5).toString());
        }
        
    }
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        truoc1();
    }//GEN-LAST:event_btn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_QLDSV;
    private javax.swing.JTextField txt_DiemTB;
    private javax.swing.JTextField txt_GDTC;
    private javax.swing.JTextField txt_HoTensvvv;
    private javax.swing.JTextField txt_Masvvv;
    private javax.swing.JTextField txt_TiengAnh;
    private javax.swing.JTextField txt_TinHoc;
    private javax.swing.JTextField txt_masVV;
    // End of variables declaration//GEN-END:variables
}
