/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai1;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author homna
 */
public class bai1 extends javax.swing.JFrame {

    /**
     * Creates new form bai1
     */
    public bai1() {
        initComponents();
        setLocationRelativeTo(null);
        
        BorderLayout borderLayout = new BorderLayout();
        GridLayout gridLayout = new GridLayout(2,5);
        
        JButton btn1 = new JButton("Button 1");
        JButton btn2 = new JButton("Button 2");
        JButton btn3 = new JButton("Button 3");
        JButton btn4 = new JButton("Button 4");
        JButton btn5 = new JButton("Button 5");
        JButton btn6 = new JButton("Button 6");
        JButton btn7 = new JButton("Button 7");
        JButton btn8 = new JButton("Button 8");
        JButton btn9 = new JButton("Button 9");
        JButton btn10 = new JButton("Button 10");
        
        jPanel2.setLayout(borderLayout);
        
        jPanel2.add(btn_north, BorderLayout.NORTH);
        jPanel2.add(btn_east, BorderLayout.EAST);
        jPanel2.add(btn_south, BorderLayout.SOUTH);
        jPanel2.add(btn_west, BorderLayout.WEST);
        jPanel2.add(btn_center, BorderLayout.CENTER);
        
        jPanel3.setLayout(gridLayout);
        jPanel3.add(btn1);
        jPanel3.add(btn2);
        jPanel3.add(btn3);
        jPanel3.add(btn4);
        jPanel3.add(btn5);
        jPanel3.add(btn6);
        jPanel3.add(btn7);
        jPanel3.add(btn8);
        jPanel3.add(btn9);
        jPanel3.add(btn10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_red = new javax.swing.JButton();
        btn_green = new javax.swing.JButton();
        btn_yellow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_north = new javax.swing.JButton();
        btn_east = new javax.swing.JButton();
        btn_south = new javax.swing.JButton();
        btn_west = new javax.swing.JButton();
        btn_center = new javax.swing.JButton();
        txtComment = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        btn_red.setText("Red");
        btn_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redActionPerformed(evt);
            }
        });
        jPanel1.add(btn_red);

        btn_green.setText("Green");
        btn_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_greenActionPerformed(evt);
            }
        });
        jPanel1.add(btn_green);

        btn_yellow.setText("Yellow");
        btn_yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yellowActionPerformed(evt);
            }
        });
        jPanel1.add(btn_yellow);

        btn_north.setText("North");
        btn_north.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_northActionPerformed(evt);
            }
        });

        btn_east.setText("East");
        btn_east.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eastActionPerformed(evt);
            }
        });

        btn_south.setText("South");
        btn_south.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_southActionPerformed(evt);
            }
        });

        btn_west.setText("West");
        btn_west.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_westActionPerformed(evt);
            }
        });

        btn_center.setText("Center");
        btn_center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_centerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btn_north)
                .addGap(64, 64, 64)
                .addComponent(btn_east)
                .addGap(27, 27, 27)
                .addComponent(btn_south)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_west)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_center)
                .addGap(187, 187, 187))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_north))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_east)
                            .addComponent(btn_south)
                            .addComponent(btn_west))))
                .addGap(18, 18, 18)
                .addComponent(btn_center)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        txtComment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtComment.setForeground(new java.awt.Color(0, 204, 0));
        txtComment.setText("Chào các bạn sinh viên Fpoly, Java 3");
        txtComment.setActionCommand("<Not Set>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.red);
    }//GEN-LAST:event_btn_redActionPerformed

    private void btn_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_greenActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn_greenActionPerformed

    private void btn_yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yellowActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.yellow);
    }//GEN-LAST:event_btn_yellowActionPerformed

    private void btn_northActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_northActionPerformed
        // TODO add your handling code here:
        txtComment.setText("North");
    }//GEN-LAST:event_btn_northActionPerformed

    private void btn_eastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eastActionPerformed
        // TODO add your handling code here:
        txtComment.setText("East");
    }//GEN-LAST:event_btn_eastActionPerformed

    private void btn_southActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_southActionPerformed
        // TODO add your handling code here:
        txtComment.setText("South");
    }//GEN-LAST:event_btn_southActionPerformed

    private void btn_westActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_westActionPerformed
        // TODO add your handling code here:
        txtComment.setText("West");
    }//GEN-LAST:event_btn_westActionPerformed

    private void btn_centerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_centerActionPerformed
        // TODO add your handling code here:
        txtComment.setText("Center");
    }//GEN-LAST:event_btn_centerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_center;
    private javax.swing.JButton btn_east;
    private javax.swing.JButton btn_green;
    private javax.swing.JButton btn_north;
    private javax.swing.JButton btn_red;
    private javax.swing.JButton btn_south;
    private javax.swing.JButton btn_west;
    private javax.swing.JButton btn_yellow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtComment;
    // End of variables declaration//GEN-END:variables
}
