/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import ViewModel.QuanLyMauSac;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Service.Iplm.IManagermauSacServiceIplm;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class FrmQuanLyMauSac extends javax.swing.JFrame {

    /**
     * Creates new form FrmQuanLyMauSac
     */
    DefaultTableModel dtm = new DefaultTableModel();
    List<QuanLyMauSac> listQLMauSac = new ArrayList<>();
    IManagermauSacServiceIplm imsi = new IManagermauSacServiceIplm();

    public FrmQuanLyMauSac() {
        initComponents();
        setLocationRelativeTo(null);
        tbMauSac.setModel(dtm);
        String[] mauSac = {"Id", "Mã màu Sắc", "Tên Màu Sắc"};
        dtm.setColumnIdentifiers(mauSac);
        listQLMauSac = imsi.getAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMauSac = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbId = new javax.swing.JLabel();
        btHienThiMauSac = new javax.swing.JButton();
        btThemMauSac = new javax.swing.JButton();
        btSuaMauSac = new javax.swing.JButton();
        btXoaMauSac = new javax.swing.JButton();
        txtMaMau = new javax.swing.JTextField();
        txtTenMau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbMauSac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMauSac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMauSacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMauSac);

        jLabel1.setText("Id");

        jLabel2.setText(" ");

        jLabel3.setText("Mã Màu");

        jLabel4.setText("Tên Màu");

        jlbId.setText(".");

        btHienThiMauSac.setText("Hiển Thị");
        btHienThiMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiMauSacActionPerformed(evt);
            }
        });

        btThemMauSac.setText("Thêm");
        btThemMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMauSacActionPerformed(evt);
            }
        });

        btSuaMauSac.setText("Sửa");
        btSuaMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaMauSacActionPerformed(evt);
            }
        });

        btXoaMauSac.setText("Xóa");
        btXoaMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaMauSacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btHienThiMauSac)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btThemMauSac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSuaMauSac))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jlbId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaMau, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(txtTenMau))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(114, 114, 114)
                        .addComponent(btXoaMauSac))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jlbId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTenMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHienThiMauSac)
                    .addComponent(btThemMauSac)
                    .addComponent(btSuaMauSac)
                    .addComponent(btXoaMauSac))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHienThiMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiMauSacActionPerformed
        // TODO add your handling code here:
        showDataMauSac(listQLMauSac);
    }//GEN-LAST:event_btHienThiMauSacActionPerformed

    private void btThemMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMauSacActionPerformed
        dtm.setRowCount(0);
        QuanLyMauSac newMauSac = getQLMauSac();
        if (imsi.add(newMauSac) != null) {
            JOptionPane.showMessageDialog(this, "thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại");
        }
        listQLMauSac.add(newMauSac);
    }//GEN-LAST:event_btThemMauSacActionPerformed

    private void btXoaMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaMauSacActionPerformed
        String ma = txtMaMau.getText();
        String delete = imsi.delete(ma);
        JOptionPane.showMessageDialog(this, delete);
    }//GEN-LAST:event_btXoaMauSacActionPerformed

    private void tbMauSacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMauSacMouseClicked
        int row = tbMauSac.getSelectedRow();
        fillData(row);
    }//GEN-LAST:event_tbMauSacMouseClicked

    private void btSuaMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaMauSacActionPerformed
        String ma = txtMaMau.getText();
        String ten = txtTenMau.getText();

        QuanLyMauSac qlMauSac = new QuanLyMauSac(ma, ten);
        QuanLyMauSac updateQlMauSac = imsi.update(qlMauSac, ma);
        if (updateQlMauSac != null) {
            JOptionPane.showMessageDialog(this, "thành công");
        } else {
            JOptionPane.showMessageDialog(this, "thất bại");
        }
    }//GEN-LAST:event_btSuaMauSacActionPerformed

    /**
     * @param args the command line arguments
     */
    private void fillData(int row) {
        QuanLyMauSac qlMauSac = listQLMauSac.get(row);
        jlbId.setText(qlMauSac.getId());
        txtMaMau.setText(qlMauSac.getMaMauSac());
        txtTenMau.setText(qlMauSac.getTenMauSac());
    }

    private QuanLyMauSac getQLMauSac() {
        QuanLyMauSac qlMauSac = new QuanLyMauSac();
        String maMau = txtMaMau.getText();
        qlMauSac.setMaMauSac(maMau);
        String tenMau = txtTenMau.getText();
        qlMauSac.setTenMauSac(tenMau);
        return qlMauSac;
    }

    public void showDataMauSac(List<QuanLyMauSac> listQLMauSac) {
        for (QuanLyMauSac quanLyMauSac : listQLMauSac) {
            dtm.addRow(quanLyMauSac.arriveData());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmQuanLyMauSac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmQuanLyMauSac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHienThiMauSac;
    private javax.swing.JButton btSuaMauSac;
    private javax.swing.JButton btThemMauSac;
    private javax.swing.JButton btXoaMauSac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbId;
    private javax.swing.JTable tbMauSac;
    private javax.swing.JTextField txtMaMau;
    private javax.swing.JTextField txtTenMau;
    // End of variables declaration//GEN-END:variables
}
