/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sanpham;
import service.serviceSanpham;
import serviceimpl.serviceSanphamimpl;

/**
 *
 * @author User
 */
public class QLSanpham extends javax.swing.JFrame {

    /**
     * Creates new form QLSanpham
     */
    serviceSanpham svsanpham = new serviceSanphamimpl();

    public QLSanpham() {
        initComponents();
        loadtable();
    }

    public Sanpham getdata() {
        String id = "";
        String ma = txt_ma.getText().trim().toUpperCase();
        String ten = txt_ten.getText().trim();
        if (ma.length() == 0 || ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong du lieu");
            return null;
        }
        Sanpham sp = new Sanpham(id, ma, ten);
        return sp;
    }

    public void loadtable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tb_sanpham.getModel();
        defaultTableModel.setRowCount(0);
        for (Sanpham sanpham : svsanpham.getall()) {
            defaultTableModel.addRow(new Object[]{
                sanpham.getMa(), sanpham.getTen()
            });
        }
    }

    public void clearform() {
        txt_ma.setText("");
        txt_ten.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_them = new javax.swing.JButton();
        txt_sua = new javax.swing.JButton();
        txt_xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sanpham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quan Ly san Pham");

        jLabel2.setText("Ma");

        jLabel3.setText("Ten");

        txt_them.setText("them");
        txt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_themActionPerformed(evt);
            }
        });

        txt_sua.setText("sua");
        txt_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_suaActionPerformed(evt);
            }
        });

        txt_xoa.setText("xoa");
        txt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xoaActionPerformed(evt);
            }
        });

        tb_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma", "Ten"
            }
        ));
        tb_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sanpham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ma)
                                    .addComponent(txt_ten, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_them)
                                    .addComponent(txt_sua)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(txt_xoa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_them)
                    .addComponent(txt_xoa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sanphamMouseClicked
        // TODO add your handling code here:
        int row = tb_sanpham.getSelectedRow();
        txt_ma.setText(tb_sanpham.getValueAt(row, 0).toString());
        txt_ten.setText(tb_sanpham.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tb_sanphamMouseClicked

    private void txt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_themActionPerformed
        // TODO add your handling code here:
        Sanpham sp = this.getdata();
        if (sp == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, svsanpham.insert(sp));
        loadtable();
        clearform();

    }//GEN-LAST:event_txt_themActionPerformed

    private void txt_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_suaActionPerformed
        // TODO add your handling code here:
        Sanpham sp = this.getdata();
        if (sp == null) {
            return;
        }
        int row = tb_sanpham.getSelectedRow();
        String ma = tb_sanpham.getValueAt(row, 0).toString();

        JOptionPane.showMessageDialog(this, svsanpham.update(sp, ma));
        loadtable();
        clearform();
    }//GEN-LAST:event_txt_suaActionPerformed

    private void txt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xoaActionPerformed
        // TODO add your handling code here:
        int row = tb_sanpham.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chay chon dong de xoa");
            return;
        }
        String ma = tb_sanpham.getValueAt(row, 0).toString();
        JOptionPane.showMessageDialog(this, svsanpham.delete(ma));
        loadtable();
        clearform();
    }//GEN-LAST:event_txt_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_sanpham;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JButton txt_sua;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JButton txt_them;
    private javax.swing.JButton txt_xoa;
    // End of variables declaration//GEN-END:variables
}
