/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.QuanLyBan;
import Repository.QuanLyBanRepository;
import Service.QLBService;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tt
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    QuanLyBanRepository qlb = new QuanLyBanRepository();
    QuanLyBan alb = new QuanLyBan();
    QLBService qlbSV = new QLBService();
    DefaultTableModel defaultTableModel;
    public UI() {
        initComponents();
        setLocationRelativeTo(null);
 
    }
    public void loadData(){
        defaultTableModel = (DefaultTableModel) tb_QuanLy.getModel();
        defaultTableModel.setRowCount(0);
        for (QuanLyBan qlb : qlbSV.getList()) {
            Object[] rowData = {
                qlb.getMa(),qlb.getTen(),qlb.getNgaySinh(),qlb.getSoThich(),qlb.ConLienLac()
            };
            defaultTableModel.addRow(rowData);
        }
    }
    private QuanLyBan getForm(){
        String ma = lblMa.getText();
        String ten = txt_Ten.getText().trim();
        String ngaysinh = txt_NgaySinh.getText().trim();
        String sothich = txt_SoThich.getText().trim();
        if(ten.length()==0||ngaysinh.length()==0||sothich.length()==0){
            JOptionPane.showMessageDialog(this, "Thong tin khong de trong");
            return null;
        }
        int lienhe = 1;
        if(chk_linlac.isSelected()){
            lienhe=0;
        }
        Date ngaySinh = null;
        try {
            ngaySinh = Date.valueOf(ngaysinh);
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        }
        QuanLyBan qlb1 = new QuanLyBan(ma, ten, ngaySinh, sothich, lienhe);
        return qlb1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_QuanLy = new javax.swing.JTable();
        lblMa = new javax.swing.JLabel();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_Ten = new javax.swing.JTextField();
        txt_SoThich = new javax.swing.JTextField();
        chk_linlac = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma Ban:");

        jLabel2.setText("Ngay Sinh");

        jLabel3.setText("Ten Ban");

        jLabel4.setText("So Thich");

        btn_them.setText("Hien thi");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setText("Sua");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xoa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        tb_QuanLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ma Ban", "Ten Ban", "Ngay Sinh", "So Thich", "Lien Lac"
            }
        ));
        tb_QuanLy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_QuanLyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_QuanLy);

        lblMa.setText("-");

        chk_linlac.setText("Con Lien Lac");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addGap(42, 42, 42)
                        .addComponent(btn_sua)
                        .addGap(36, 36, 36)
                        .addComponent(btn_xoa)
                        .addGap(118, 118, 118)
                        .addComponent(chk_linlac, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Ten)
                            .addComponent(txt_SoThich, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(lblMa)
                    .addComponent(txt_Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SoThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa)
                    .addComponent(chk_linlac))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_QuanLyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_QuanLyMouseClicked
        int row = tb_QuanLy.getSelectedRow();
        lblMa.setText(tb_QuanLy.getValueAt(row, 0).toString());
        txt_Ten.setText(tb_QuanLy.getValueAt(row, 1).toString());
        txt_NgaySinh.setText(tb_QuanLy.getValueAt(row, 2).toString());
        txt_SoThich.setText(tb_QuanLy.getValueAt(row, 3).toString());
        if(tb_QuanLy.getValueAt(row, 4).toString().equals("Con")){
            chk_linlac.setSelected(true);
        }else{
            chk_linlac.setSelected(false);
        }
        
    }//GEN-LAST:event_tb_QuanLyMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int row = tb_QuanLy.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Chon 1 dong roi xoa");
            return;
        }
        String ma = tb_QuanLy.getValueAt(row, 0).toString();
        qlbSV.delete(ma);
        loadData();
        
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
       loadData();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int row = tb_QuanLy.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this, "Chon 1 dong roi sua");
            return;
        }
        QuanLyBan qlb = getForm();
        if(qlb == null){
            return;
        }
        String ma = tb_QuanLy.getValueAt(row, 0).toString();
        qlbSV.update(qlb,qlb.getMa());
        loadData();
        
    }//GEN-LAST:event_btn_suaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JCheckBox chk_linlac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMa;
    private javax.swing.JTable tb_QuanLy;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_SoThich;
    private javax.swing.JTextField txt_Ten;
    // End of variables declaration//GEN-END:variables
}
