package view;

import control.sinhVienService;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modul.sinhVien;

public class QuanLySinhVienFrame extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private sinhVienService control = new sinhVienService();

    public QuanLySinhVienFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.getHSBColor(255, 204, 204));
    }

    public void addRows(ArrayList<sinhVien> list) {
        tableModel = (DefaultTableModel) tb_danhsach.getModel();
        tableModel.setRowCount(0);
        for (sinhVien sv : list) {
            tableModel.addRow(new Object[]{
                sv.getMaSv(),
                sv.getName(),
                sv.getDiemToan(),
                sv.getDiemVan(),
                sv.getDiemAnh(),
                sv.getDiemTB(),
                sv.getHocLuc()
            });
        }
    }

    public boolean checkData() {
        if (!txt_id.getText().equals("") && !txt_ten.getText().equals("")
                && !txt_toan.getText().equals("") && !txt_van.getText().equals("") && !txt_van.getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    public void loadForm(int row) {
        txt_id.setEditable(false);
        txt_id.setText(tb_danhsach.getValueAt(row, 0).toString());
        txt_ten.setText(tb_danhsach.getValueAt(row, 1).toString());
        txt_toan.setText(tb_danhsach.getValueAt(row, 2).toString());
        txt_van.setText(tb_danhsach.getValueAt(row, 3).toString());
        txt_anh.setText(tb_danhsach.getValueAt(row, 4).toString());
        lb_dtb.setText(tb_danhsach.getValueAt(row, 5).toString());
    }

    public void loadForm(sinhVien sv) {
        txt_id.setEditable(false);
        txt_id.setText(sv.getMaSv());
        txt_ten.setText(sv.getName());
        txt_toan.setText(sv.getDiemToan() + "");
        txt_van.setText(sv.getDiemVan() + "");
        txt_anh.setText(sv.getDiemAnh() + "");
        lb_dtb.setText(sv.getDiemTB() + "");
    }

    public sinhVien createSinhVien() {
        sinhVien sv = new sinhVien();
        sv.setMaSv(txt_id.getText().trim().toUpperCase());
        sv.setName(control.uperName(txt_ten.getText().trim()));
        try {
            sv.setDiemToan(Double.parseDouble(txt_toan.getText().trim()));
        } catch (NumberFormatException e) {
            sv.setDiemToan(-1);
        }
        try {
            sv.setDiemAnh(Double.parseDouble(txt_anh.getText().trim()));
        } catch (NumberFormatException e) {
            sv.setDiemAnh(-1);
        }
        try {
            sv.setDiemVan(Double.parseDouble(txt_van.getText().trim()));
        } catch (NumberFormatException e) {
            sv.setDiemVan(-1);
        }
        return sv;
    }

    public void clearForm() {
        txt_id.setEditable(true);
        txt_id.setText("");
        txt_ten.setText("");
        txt_toan.setText("");
        txt_van.setText("");
        txt_anh.setText("");
        lb_dtb.setText("-");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_LoGo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_toan = new javax.swing.JTextField();
        txt_van = new javax.swing.JTextField();
        txt_anh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lb_dtb = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_tim = new javax.swing.JButton();
        btn_doc = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_doc1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_danhsach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mềm Quản Lý Điểm Sinh Viên");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 120));

        lbl_LoGo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_LoGo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LoGo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_LoGo, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ ĐIỂM SINH VIÊN");

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));

        jLabel2.setText("Mã Sinh Viên:");

        jLabel3.setText("Họ Tên:");

        jLabel4.setText("Điểm Toán:");

        jLabel5.setText("Điểm Văn:");

        jLabel6.setText("Điểm Anh:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Điểm TB");

        lb_dtb.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lb_dtb.setForeground(new java.awt.Color(255, 0, 0));
        lb_dtb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dtb.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_toan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_van, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lb_dtb)
                        .addGap(16, 16, 16)))
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_toan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_van, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_dtb))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new java.awt.GridLayout(1, 10, 20, 20));

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-user.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel4.add(btn_them);

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_sua);

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_xoa);

        btn_tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btn_tim.setText("Tìm Kiếm");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });
        jPanel4.add(btn_tim);

        btn_doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/read.png"))); // NOI18N
        btn_doc.setText("Đọc File");
        btn_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_docActionPerformed(evt);
            }
        });
        jPanel4.add(btn_doc);

        btn_ghi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        btn_ghi.setText("Ghi File");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });
        jPanel4.add(btn_ghi);

        btn_doc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btn_doc1.setText("Clear");
        btn_doc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doc1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn_doc1);

        tb_danhsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sinh Viên", "Họ Tên", "Điểm Toán", "Điểm Văn", "Điểm Anh", "Điểm TB", "Học Lực"
            }
        ));
        tb_danhsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_danhsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_danhsach);
        if (tb_danhsach.getColumnModel().getColumnCount() > 0) {
            tb_danhsach.getColumnModel().getColumn(0).setResizable(false);
            tb_danhsach.getColumnModel().getColumn(0).setPreferredWidth(50);
            tb_danhsach.getColumnModel().getColumn(1).setPreferredWidth(150);
            tb_danhsach.getColumnModel().getColumn(2).setResizable(false);
            tb_danhsach.getColumnModel().getColumn(2).setPreferredWidth(35);
            tb_danhsach.getColumnModel().getColumn(3).setResizable(false);
            tb_danhsach.getColumnModel().getColumn(3).setPreferredWidth(30);
            tb_danhsach.getColumnModel().getColumn(4).setResizable(false);
            tb_danhsach.getColumnModel().getColumn(4).setPreferredWidth(30);
            tb_danhsach.getColumnModel().getColumn(5).setResizable(false);
            tb_danhsach.getColumnModel().getColumn(5).setPreferredWidth(30);
            tb_danhsach.getColumnModel().getColumn(6).setResizable(false);
            tb_danhsach.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (checkData() == true) {
            if (control.addSinhVien(createSinhVien())) {
                addRows(control.getList());
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công !");
                clearForm();
            } else
                JOptionPane.showMessageDialog(rootPane, "Thêm thất bại !");
        } else
            JOptionPane.showMessageDialog(rootPane, "Thêm thất bại !");
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        int row = tb_danhsach.getSelectedRow();
        if (row>=0) {
            String maSv = tb_danhsach.getValueAt(row, 0).toString();
            if (control.updateSinhVien(maSv, createSinhVien()) == true) {
                int choose = JOptionPane.showConfirmDialog(rootPane, "Xác Nhận Sửa ?");
                if (choose == JOptionPane.YES_OPTION) {
                    addRows(control.getList());
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công !");
                    clearForm();
                } else
                    JOptionPane.showMessageDialog(rootPane, "Hủy cập nhật !");
            } else 
                JOptionPane.showMessageDialog(rootPane, "Không thể cập nhật !");
        } else
            JOptionPane.showMessageDialog(rootPane, "Bạn Chưa chọn đối tượng cần sửa !");
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int row = tb_danhsach.getSelectedRow();
        if (row>=0) {
            String maSv = tb_danhsach.getValueAt(row, 0).toString();
            int choose = JOptionPane.showConfirmDialog(rootPane, "Xác nhận xóa ?");
            if (choose == JOptionPane.YES_OPTION) {
                control.deleteSinhVien(maSv);
                addRows(control.getList());
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công !");
                clearForm();
            } else
                JOptionPane.showMessageDialog(rootPane, "Hủy xóa !");
        } else
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn đối tượng cần xóa !");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        String maSv = JOptionPane.showInputDialog(this,"Nhập mã sinh viên","Tìm Kiếm",JOptionPane.OK_OPTION);
        if (control.searchSinhVien(maSv) != null) {
            loadForm(control.searchSinhVien(maSv));
            JOptionPane.showMessageDialog(rootPane, "Tìm thây sinh viên có mã " + maSv);
        } else
            JOptionPane.showMessageDialog(rootPane, "Không tìm thây sinh viên có mã " + maSv);
    }//GEN-LAST:event_btn_timActionPerformed

    private void btn_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_docActionPerformed
        // TODO add your handling code here:
        if (control.checkFile() == false) {
            addRows(control.getList());
        } else
            addRows(control.readFile());
        JOptionPane.showMessageDialog(this, "Đọc File thành công!!");
    }//GEN-LAST:event_btn_docActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        control.writeFile();
        JOptionPane.showMessageDialog(rootPane, "Ghi File thành công !");
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void tb_danhsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_danhsachMouseClicked
        // TODO add your handling code here:
        int row = tb_danhsach.getSelectedRow();
        loadForm(row);
    }//GEN-LAST:event_tb_danhsachMouseClicked

    private void btn_doc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doc1ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btn_doc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doc;
    private javax.swing.JButton btn_doc1;
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_dtb;
    private javax.swing.JLabel lbl_LoGo;
    private javax.swing.JTable tb_danhsach;
    private javax.swing.JTextField txt_anh;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_toan;
    private javax.swing.JTextField txt_van;
    // End of variables declaration//GEN-END:variables
}
